---
#apstra:
#  username: "admin"
#  password: "S3kom123!"
#  baseurl: "https://10.106.20.29/api"
#bp_name: "ISA-BP"          ### Blueprint name

  
bp_name: "apstra-pod1"          ### Blueprint name
apstra:
  username: "admin"
  password: "ReasonableBobolink6$"
  baseurl: "https://15.237.142.103:40409/api"
